[changelog]
commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^refactor", group = "changed" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^.*", group = "other" },
]

[workspace]
git_tag_enable = false

[[package]]
name = "compio"
git_tag_enable = true
git_tag_name = "v{{ version }}"
