name: Lint Commit Messages
on:
  merge_group:
    types: [checks_requested]
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wagoid/commitlint-github-action@v6
