name: Check iOS

on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - master
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'rust-toolchain.toml'
      - '.github/workflows/ci_check_ios.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'rust-toolchain.toml'
      - '.github/workflows/ci_check_ios.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check_ios:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-ios
          - aarch64-apple-ios-macabi
    steps:
      - uses: actions/checkout@v6
      - name: Setup target
        run: rustup target add ${{ matrix.target }}
      - name: Check clippy
        shell: bash
        run: |
          cargo clippy --target ${{ matrix.target }} --all-features --all-targets -- -Dwarnings
