name: Check Code Format

on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - master
    paths:
      - 'rust-toolchain.toml'
      - 'rustfmt.toml'
      - '**/Cargo.toml'
      - '**/*.rs'
      - '.github/workflows/ci_format.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'rust-toolchain.toml'
      - 'rustfmt.toml'
      - '**/*.rs'
      - '.github/workflows/ci_format.yml'

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Check Format
        run: cargo fmt --all -- --check
