name: TestASan

on:
  push:
    branches:
      - master
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'scripts/asan.sh'
      - 'scripts/asan.supp'
      - '.github/workflows/ci_test_asan.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - 'scripts/asan.sh'
      - 'scripts/asan.supp'
      - '.github/workflows/ci_test_asan.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup nightly toolchain with rust-src
        run: rustup toolchain install nightly --component rust-src
      - name: Run ASan tests
        run: ./scripts/asan.sh x86_64-unknown-linux-gnu
